In [1]:
# Import packages

library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
final.hcris.v2010<-read_csv('../../hwk4/data/output/HCRIS_Data_v2010.csv', show_col_types = FALSE)

In [3]:
glimpse(final.hcris.v2010)

Rows: 57,802
Columns: 48
$ report                       <dbl> 235, 268, 298, 522, 700, 959, 1001, 1091,…
$ provider_number              <chr> "492007", "044017", "193070", "191311", "…
$ npi                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ fy_start                     <chr> "06/01/2010", "07/01/2010", "07/01/2010",…
$ fy_end                       <chr> "05/31/2011", "06/30/2011", "06/30/2011",…
$ date_processed               <chr> "05/22/2012", "05/22/2012", "05/24/2012",…
$ date_created                 <chr> "05/21/2012", "05/22/2012", "05/22/2012",…
$ status                       <dbl> 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 5, 1, 1, 1,…
$ year                         <dbl> 2010, 2010, 2010, 2010, 2010, 2010, 2010,…
$ data_source                  <chr> "v2010", "v2010", "v2010", "v2010", "v201…
$ beds                         <dbl> 35, 16, 15, 25, 25, 125, 417, 62, 33, 17,…
$ tot_charges                  <dbl> 28099723, 22570813, 12710268, 24562552, 3…
$ tot_discounts                <dbl> 16813631, 13887610, 8003304, 13266399, 20…
$ net_pat_rev                  <dbl> 11286092, 8683203, 4706964, 11296153, 164…
$ tot_operating_exp            <dbl> 10992855, 14035648, 4663815, 12556463, 24…
$ ip_charges                   <dbl> 28099723, 6465577, 1603125, 342650, 11393…
$ icu_charges                  <dbl> NA, NA, NA, NA, 1136264, NA, NA, NA, NA, …
$ ancillary_charges            <dbl> NA, 1244402, 2081241, 2351078, 6897534, N…
$ tot_discharges               <dbl> 284, 486, 65, 378, 683, 202, 758, 155, 24…
$ mcare_discharges             <dbl> 212, NA, 42, 195, 292, 7, 85, 14, 22, NA,…
$ mcaid_discharges             <dbl> NA, 184, 5, 102, 44, 28, 428, 5, 8, 104, …
$ tot_mcare_payment            <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1…
$ secondary_mcare_payment      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5…
$ street                       <chr> "600 GRESHAM DRIVE  SUITE 700", "1601 MUR…
$ city                         <chr> "NORFOLK", "MAUMELLE", "BATON ROUGE", "BU…
$ state                        <chr> "VA", "AR", "LA", "LA", "NC", "CT", "NY",…
$ zip                          <chr> "23507-1904", "72213", "70802", "71322-",…
$ county                       <chr> "CITY OF NORFOLK", "PULASKI", "EAST BATON…
$ name                         <chr> "HOSPITAL FOR EXTENDED RECOVERY", "UNITED…
$ hvbp_payment                 <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ hrrp_payment                 <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ tot_uncomp_care_charges      <dbl> 650644, NA, NA, NA, 1156943, NA, NA, NA, …
$ tot_uncomp_care_partial_pmts <dbl> NA, NA, NA, NA, 26360, NA, NA, NA, NA, NA…
$ bad_debt                     <dbl> 122844, NA, -391675, -184005, 8376396, NA…
$ cost_to_charge               <dbl> 0.388128, 0.441042, 0.294707, 0.484379, 0…
$ new_cap_ass                  <dbl> 11062, 125970, NA, 513293, 5970986, 21710…
$ cash                         <dbl> 2675573, NA, -58146, 2190059, 3320459, NA…
$ fixed_assets                 <dbl> 427510, 2098425, 67892, 3339233, 29863383…
$ depr_land                    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, -9809…
$ depr_bldg                    <dbl> NA, -1339280, NA, NA, -7935442, NA, NA, N…
$ depr_lease                   <dbl> -26113, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ depr_fixed_equip             <dbl> -4914, NA, NA, NA, NA, NA, NA, NA, NA, -5…
$ depr_auto                    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ depr_major_equip             <dbl> -246717, NA, -1993, -4702450, -1940327, N…
$ depr_minor_equip             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ depr_HIT                     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ current_assets               <dbl> 6935058, 3037753, 1148904, 4257114, 10513…
$ current_liabilities          <dbl> 1370000, 731870, 372399, 938136, 3662567,…

In [4]:
medicaid.data <- read_csv('../data/medicaid-exp-data2.csv', show_col_types = FALSE)

In [11]:
head(medicaid.data)

  State Status of Medicaid Expansion Decision Expansion Year
1 AL    Not Adopted                           N/A
2 AK    Adopted                               2015
3 AZ    Adopted                               2014
4 AR    Adopted                               2014
5 CA    Adopted                               2014
6 CO    Adopted                               2014

In [6]:
head(final.hcris.v2010)

  report provider_number npi fy_start   fy_end     date_processed date_created
1 235    492007          NA  06/01/2010 05/31/2011 05/22/2012     05/21/2012
2 268    044017          NA  07/01/2010 06/30/2011 05/22/2012     05/22/2012
3 298    193070          NA  07/01/2010 06/30/2011 05/24/2012     05/22/2012
4 522    191311          NA  07/01/2010 06/30/2011 05/25/2012     05/25/2012
5 700    341311          NA  07/01/2010 06/30/2011 06/08/2012     06/07/2012
6 959    072006          NA  07/01/2010 06/30/2011 06/14/2012     06/13/2012
  status year data_source ⋯ depr_land depr_bldg depr_lease depr_fixed_equip
1 2      2010 v2010       ⋯ NA              NA  -26113     -4914
2 1      2010 v2010       ⋯ NA        -1339280      NA        NA
3 1      2010 v2010       ⋯ NA              NA      NA        NA
4 1      2010 v2010       ⋯ NA              NA      NA        NA
5 1      2010 v2010       ⋯ NA        -7935442      NA        NA
6 2      2010 v2010       ⋯ NA              NA      NA        NA
  depr_auto depr_major_equip depr_minor_equip depr_HIT current_assets
1 NA         -246717         NA               NA        6935058
2 NA              NA         NA               NA        3037753
3 NA           -1993         NA               NA        1148904
4 NA        -4702450         NA               NA        4257114
5 NA        -1940327         NA               NA       10513916
6 NA              NA         NA               NA             NA
  current_liabilities
1 1370000
2  731870
3  372399
4  938136
5 3662567
6      NA

In [7]:
glimpse(medicaid.data)

Rows: 51
Columns: 3
$ State                                   <chr> "AL", "AK", "AZ", "AR", "CA", …
$ `Status of Medicaid Expansion Decision` <chr> "Not Adopted", "Adopted", "Ado…
$ `Expansion Year`                        <chr> "N/A", "2015", "2014", "2014",…

In [19]:
# Merge data 

merged_data <- final.hcris.v2010 %>%
  left_join(medicaid.data, by = "state")

merged_data <- merged_data %>%
  mutate(exp_year = as.numeric(exp_year))

Warning message:
“There was 1 warning in `mutate()`.
ℹ In argument: `exp_year = as.numeric(exp_year)`.
Caused by warning:
! NAs introduced by coercion”

In [21]:
summary(merged_data$medicaid_exp_status)

   Length     Class      Mode
    57802 character character

In [22]:
glimpse(merged_data)

Rows: 57,802
Columns: 50
$ report                       <dbl> 235, 268, 298, 522, 700, 959, 1001, 1091,…
$ provider_number              <chr> "492007", "044017", "193070", "191311", "…
$ npi                          <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ fy_start                     <chr> "06/01/2010", "07/01/2010", "07/01/2010",…
$ fy_end                       <chr> "05/31/2011", "06/30/2011", "06/30/2011",…
$ date_processed               <chr> "05/22/2012", "05/22/2012", "05/24/2012",…
$ date_created                 <chr> "05/21/2012", "05/22/2012", "05/22/2012",…
$ status                       <dbl> 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 5, 1, 1, 1,…
$ year                         <dbl> 2010, 2010, 2010, 2010, 2010, 2010, 2010,…
$ data_source                  <chr> "v2010", "v2010", "v2010", "v2010", "v201…
$ beds                         <dbl> 35, 16, 15, 25, 25, 125, 417, 62, 33, 17,…
$ tot_charges                  <dbl> 28099723, 22570813, 12710268, 24562552, 3…
$ tot_discounts                <dbl> 16813631, 13887610, 8003304, 13266399, 20…
$ net_pat_rev                  <dbl> 11286092, 8683203, 4706964, 11296153, 164…
$ tot_operating_exp            <dbl> 10992855, 14035648, 4663815, 12556463, 24…
$ ip_charges                   <dbl> 28099723, 6465577, 1603125, 342650, 11393…
$ icu_charges                  <dbl> NA, NA, NA, NA, 1136264, NA, NA, NA, NA, …
$ ancillary_charges            <dbl> NA, 1244402, 2081241, 2351078, 6897534, N…
$ tot_discharges               <dbl> 284, 486, 65, 378, 683, 202, 758, 155, 24…
$ mcare_discharges             <dbl> 212, NA, 42, 195, 292, 7, 85, 14, 22, NA,…
$ mcaid_discharges             <dbl> NA, 184, 5, 102, 44, 28, 428, 5, 8, 104, …
$ tot_mcare_payment            <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1…
$ secondary_mcare_payment      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 5…
$ street                       <chr> "600 GRESHAM DRIVE  SUITE 700", "1601 MUR…
$ city                         <chr> "NORFOLK", "MAUMELLE", "BATON ROUGE", "BU…
$ state                        <chr> "VA", "AR", "LA", "LA", "NC", "CT", "NY",…
$ zip                          <chr> "23507-1904", "72213", "70802", "71322-",…
$ county                       <chr> "CITY OF NORFOLK", "PULASKI", "EAST BATON…
$ name                         <chr> "HOSPITAL FOR EXTENDED RECOVERY", "UNITED…
$ hvbp_payment                 <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ hrrp_payment                 <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ tot_uncomp_care_charges      <dbl> 650644, NA, NA, NA, 1156943, NA, NA, NA, …
$ tot_uncomp_care_partial_pmts <dbl> NA, NA, NA, NA, 26360, NA, NA, NA, NA, NA…
$ bad_debt                     <dbl> 122844, NA, -391675, -184005, 8376396, NA…
$ cost_to_charge               <dbl> 0.388128, 0.441042, 0.294707, 0.484379, 0…
$ new_cap_ass                  <dbl> 11062, 125970, NA, 513293, 5970986, 21710…
$ cash                         <dbl> 2675573, NA, -58146, 2190059, 3320459, NA…
$ fixed_assets                 <dbl> 427510, 2098425, 67892, 3339233, 29863383…
$ depr_land                    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, -9809…
$ depr_bldg                    <dbl> NA, -1339280, NA, NA, -7935442, NA, NA, N…
$ depr_lease                   <dbl> -26113, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ depr_fixed_equip             <dbl> -4914, NA, NA, NA, NA, NA, NA, NA, NA, -5…
$ depr_auto                    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ depr_major_equip             <dbl> -246717, NA, -1993, -4702450, -1940327, N…
$ depr_minor_equip             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ depr_HIT                     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ current_assets               <dbl> 6935058, 3037753, 1148904, 4257114, 10513…
$ current_liabilities          <dbl> 1370000, 731870, 372399, 938136, 3662567,…
$ medicaid_exp_status          <chr> "Adopted", "Adopted", "Adopted", "Adopted…
$ exp_year                     <dbl> 2019, 2014, 2016, 2016, 2023, 2014, 2014,…

In [23]:
write_csv(merged_data, "../data/output/final_exp_data.csv")